import { GLOBAL_COMMANDS } from '..';

export type KeyboardShortcutMap = Record<string, GLOBAL_COMMANDS>;

export const shortcuts: KeyboardShortcutMap = {
	'CmdOrCtrl+N': GLOBAL_COMMANDS.CREATE_NOTE,
	'CmdOrCtrl+W': GLOBAL_COMMANDS.CLOSE_CURRENT_NOTE,
	'CmdOrCtrl+Shift+T': GLOBAL_COMMANDS.RESTORE_CLOSED_NOTE,

	'CmdOrCtrl+H': GLOBAL_COMMANDS.OPEN_CURRENT_NOTE_HISTORY,

	'CmdOrCtrl+PageDown': GLOBAL_COMMANDS.FOCUS_NEXT_NOTE,
	'CmdOrCtrl+PageUp': GLOBAL_COMMANDS.FOCUS_PREVIOUS_NOTE,

	'CmdOrCtrl+L': GLOBAL_COMMANDS.LOCK_CURRENT_PROFILE,
	'CmdOrCtrl+S': GLOBAL_COMMANDS.SYNC_DATABASE,

	'CmdOrCtrl+Shift+A': GLOBAL_COMMANDS.TOGGLE_CURRENT_NOTE_ARCHIVE,
	'CmdOrCtrl+Shift+B': GLOBAL_COMMANDS.TOGGLE_CURRENT_NOTE_BOOKMARK,

	'CmdOrCtrl+Delete': GLOBAL_COMMANDS.DELETE_CURRENT_NOTE_TO_BIN,
	'CmdOrCtrl+Shift+Delete': GLOBAL_COMMANDS.DELETE_CURRENT_NOTE_PERMANENTLY,
	'CmdOrCtrl+Shift+R': GLOBAL_COMMANDS.RESTORE_CURRENT_NOTE_FROM_BIN,
};
