export enum Shortcuts {
	CREATE_NOTE,
	CLOSE_CURRENT_NOTE,
	RESTORE_CLOSED_NOTE,
	FOCUS_NEXT_NOTE,
	FOCUS_PREVIOUS_NOTE,

	TOGGLE_CURRENT_NOTE_ARCHIVE,
	TOGGLE_CURRENT_NOTE_BOOKMARK,

	DELETE_NOTE_TO_BIN,
	DELETE_NOTE_PERMANENTLY,
	RESTORE_NOTE_FROM_BIN,

	TOGGLE_CURRENT_NOTE_HISTORY_PANEL,

	LOCK_CURRENT_PROFILE,
	SYNC_DATABASE,

	FOCUS_SEARCH,
}

export const SHORTCUTS_MAP = {
	'CmdOrCtrl+N': Shortcuts.CREATE_NOTE,
	'CmdOrCtrl+W': Shortcuts.CLOSE_CURRENT_NOTE,
	'CmdOrCtrl+Shift+T': Shortcuts.RESTORE_CLOSED_NOTE,
	'CmdOrCtrl+PageDown': Shortcuts.FOCUS_NEXT_NOTE,
	'CmdOrCtrl+PageUp': Shortcuts.FOCUS_PREVIOUS_NOTE,

	'CmdOrCtrl+Shift+A': Shortcuts.TOGGLE_CURRENT_NOTE_ARCHIVE,
	'CmdOrCtrl+Shift+B': Shortcuts.TOGGLE_CURRENT_NOTE_BOOKMARK,

	'CmdOrCtrl+Delete': Shortcuts.DELETE_NOTE_TO_BIN,
	'CmdOrCtrl+Shift+Delete': Shortcuts.DELETE_NOTE_PERMANENTLY,
	'CmdOrCtrl+Shift+R': Shortcuts.RESTORE_NOTE_FROM_BIN,

	'CmdOrCtrl+H': Shortcuts.TOGGLE_CURRENT_NOTE_HISTORY_PANEL,

	'CmdOrCtrl+L': Shortcuts.LOCK_CURRENT_PROFILE,
	'CmdOrCtrl+S': Shortcuts.SYNC_DATABASE,

	'CmdOrCtrl+F': Shortcuts.FOCUS_SEARCH,
};
