import { formatAlgorithmsToString } from './utils';
import { ENCRYPTION_ALGORITHM } from '.';

export const ENCRYPTION_ALGORITHMS_LIST = [
	ENCRYPTION_ALGORITHM.AES,
	ENCRYPTION_ALGORITHM.TWOFISH,
	formatAlgorithmsToString([ENCRYPTION_ALGORITHM.AES, ENCRYPTION_ALGORITHM.TWOFISH]),
	formatAlgorithmsToString([ENCRYPTION_ALGORITHM.TWOFISH, ENCRYPTION_ALGORITHM.AES]),
];
