import { formatAlgorithms } from './utils';
import { ENCRYPTION_ALGORITHM } from '.';

export const ENCRYPTION_ALGORITHM_OPTIONS = [
	ENCRYPTION_ALGORITHM.AES,
	ENCRYPTION_ALGORITHM.TWOFISH,
	ENCRYPTION_ALGORITHM.SERPENT,
	ENCRYPTION_ALGORITHM.XChaCha20,

	formatAlgorithms([ENCRYPTION_ALGORITHM.XChaCha20, ENCRYPTION_ALGORITHM.AES]),
	formatAlgorithms([ENCRYPTION_ALGORITHM.XChaCha20, ENCRYPTION_ALGORITHM.TWOFISH]),

	formatAlgorithms([
		ENCRYPTION_ALGORITHM.AES,
		ENCRYPTION_ALGORITHM.TWOFISH,
		ENCRYPTION_ALGORITHM.SERPENT,
	]),

	formatAlgorithms([
		ENCRYPTION_ALGORITHM.XChaCha20,
		ENCRYPTION_ALGORITHM.AES,
		ENCRYPTION_ALGORITHM.SERPENT,
	]),
	formatAlgorithms([
		ENCRYPTION_ALGORITHM.XChaCha20,
		ENCRYPTION_ALGORITHM.TWOFISH,
		ENCRYPTION_ALGORITHM.SERPENT,
	]),
	formatAlgorithms([
		ENCRYPTION_ALGORITHM.XChaCha20,
		ENCRYPTION_ALGORITHM.AES,
		ENCRYPTION_ALGORITHM.TWOFISH,
	]),
];
