import { formatAlgorithms } from './utils';
import { ENCRYPTION_ALGORITHM } from '.';

export const ENCRYPTION_ALGORITHM_OPTIONS = [
	ENCRYPTION_ALGORITHM.AES,
	ENCRYPTION_ALGORITHM.TWOFISH,
	formatAlgorithms([ENCRYPTION_ALGORITHM.AES, ENCRYPTION_ALGORITHM.TWOFISH]),
	formatAlgorithms([ENCRYPTION_ALGORITHM.TWOFISH, ENCRYPTION_ALGORITHM.AES]),
];
