version: "3.9"

services:
  transmart:
    build:
        context: ./docker/transmart
        dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src/i18n/locales:/app/locales
      - .cache/locales:/app/locales/.cache
      - ./transmart.config.js:/app/transmart.config.js
    env_file:
      .env
    # environment:
    #   OPENAI_API_KEY: ${OPENROUTER_API_KEY}
    #   OPENAI_API_URL: https://openrouter.ai/api/v1
    #   TRANSMART_MODEL: openai/gpt-4o-mini